# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goreleasertest < Formula
  desc ""
  homepage "https://github.com/atileren/goreleasertest"
  version "0.0.3"

  on_macos do
    url "https://github.com/atileren/goreleasertest/releases/download/v0.0.3/goreleasertest_0.0.3_darwin_all.tar.gz"
    sha256 "b99f3e76b4041b41d419070ed2756ba722b8c7d13e0854b8a035ea971c76d5a6"

    def install
      bin.install "goreleasertest"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atileren/goreleasertest/releases/download/v0.0.3/goreleasertest_0.0.3_linux_arm64.tar.gz"
      sha256 "c4e3e43eda2e3926c11fb02bbda4af334287dfbc1da1228dcfa1005e343b0a5e"

      def install
        bin.install "goreleasertest"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/atileren/goreleasertest/releases/download/v0.0.3/goreleasertest_0.0.3_linux_amd64.tar.gz"
      sha256 "22f21c57fe6bd808ca812205840db124cf0cfce6eeb499dd94eada8fd3ff32a3"

      def install
        bin.install "goreleasertest"
      end
    end
  end
end
